{{- if .Values.prometheus.serviceMonitors.enabled }}
{{- if .Values.prometheus.serviceMonitors.backend.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-monitor
  namespace: {{ .Release.Namespace }}
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  endpoints:
    - port: http
      path: /metrics
---
{{- end }}
{{- if .Values.prometheus.serviceMonitors.frontend.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: frontend-monitor
  namespace: {{ .Release.Namespace }}
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  endpoints:
    - port: http
      path: /metrics
---
{{- end }}
{{- if .Values.prometheus.serviceMonitors.mongodb.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mongodb-monitor
  namespace: {{ .Release.Namespace }}
  labels:
    app: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  endpoints:
    - port: mongodb
      path: /metrics
{{- end }}
{{- end }}