apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "grafana.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "grafana.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "grafana.labels" . | nindent 8 }}
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:latest
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          volumeMounts:
            - name: grafana-datasources
              mountPath: /etc/grafana/provisioning/datasources
            - name: grafana-provisioning
              mountPath: /etc/grafana/provisioning/dashboards
            - name: grafana-dashboards
              mountPath: /var/lib/grafana/dashboards
            {{- if .Values.grafana.persistence.enabled }}
            - name: storage
              mountPath: /var/lib/grafana
            {{- end }}
          env:
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "grafana.fullname" . }}
                  key: admin-password
      volumes:
        - name: grafana-datasources
          configMap:
            name: {{ include "grafana.fullname" . }}-datasources
        - name: grafana-provisioning
          configMap:
            name: {{ include "grafana.fullname" . }}-provisioning
        - name: grafana-dashboards
          configMap:
            name: {{ include "grafana.fullname" . }}-dashboards
        {{- if .Values.grafana.persistence.enabled }}
        - name: storage
          persistentVolumeClaim:
            claimName: {{ include "grafana.fullname" . }}
        {{- end }}