apiVersion: v1
kind: Secret
metadata:
  name: grafana
  namespace: {{ .Release.Namespace }}
  labels:
    app: grafana
type: Opaque
data:
  admin-password: {{ .Values.grafana.adminPassword | b64enc }}