apiVersion: v1
global:
  environment: production
  # domain: example.com
backend:
  enabled: true
  replicaCount: 1
  image:
    repository: jameslee/vue-hello-world
    tag: 1.0.0
  config:
    mongoUrl: mongodb://mongodb-service:27017/myapp
    port: 3000

frontend:
  enabled: true
  replicaCount: 1
  image:
    repository: jameslee/vue-hello-world
    tag: 1.0.0
  config:
    apiUrl: http://backend-service:3000

mongodb:
  enabled: true
  persistence:
    enabled: true
    size: 100Mi
  auth:
    rootPassword: admin-password
    database: myapp

nginx:
  enabled: true
  replicaCount: 1
prometheus:
  enabled: true
  retention:
    time: 15d
    size: 50GB
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi
  serviceMonitors:
    enabled: true
    backend:
      enabled: true
    frontend:
      enabled: true
    mongodb:
      enabled: true

grafana:
  enabled: true
  adminPassword: your-secure-password
  ingress:
    enabled: false

# replicaCount: 2

# image:
#   repository: nginx
#   tag: "1.19"
#   pullPolicy: IfNotPresent

# service:
#   type: ClusterIP
#   port: 80

# ingress:
#   enabled: false     # Disabled ingress