apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.config.port }}
  selector:
    app: backend