replicaCount: 2
image:
  repository: gcr.io/google-samples/hello-app
  tag: 1.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

config:
  mongoUrl: mongodb://mongodb-service:27017/myapp
  port: 3000

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi